### ISSUE TITLE
Portfolio

### ISSUE THREAD

**Issue by chuckdee68** [smcdougall/startbootstrap-freelancer-pico#2]
Great port!  One question about the portfolio- it seems to pull the pages from content that are not feed or index; how do those pages need to be formatted to be picked up?

**Comment by mayamcdougall** [comment]
Closing because this is so old.

Sorry for never replying to this.  I was away from GitHub for a few *years*. 😅

There's a new version out now at [mayamcdougall/freelancer-pico](https://github.com/mayamcdougall/freelancer-pico).

I'm archiving this repo, as the new version is a complete rewrite.

Take care.
